name: 'Dynmap-GriefPrevention'
main: 'org.dynmap.griefprevention.DynmapGriefPreventionPlugin'
version: "${project.version}"
authors: ['mikeprimm', 'stumper66']
depend: [ 'dynmap', 'GriefPrevention' ]
api-version: '1.13'
website: 'https://github.com/stumper66/Dynmap-GriefPrevention'